server:
  port: 9001

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  artemis:
    user: developer
    password: developer
    brokerUrl: tcp://localhost:61616

jms:
  queue:
    destination:
      listen: REQUEST
      send:
        error: ERROR
        response: RESPONSE

scheduler:
  contract:
    timeout: 5000
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

datasource:
  xsd:
    path: "/xsd/"