server:
  port: 8082
spring:
  artemis:
    user: developer
    password: developer
    brokerUrl: tcp://localhost:61616
jms:
  queue:
    destination: REQUEST
datasource:
  xml:
    read:
      path: "/read-gen/"
